version: 0.20150918.{build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
shallow_clone: true
clone_folder: c:\Aura_OS

init:
- cmd: |
    git clone https://github.com/aura-systems/Cosmos.git c:\Cosmos --depth 1
    git clone https://github.com/aura-systems/XSharp.git c:\XSharp --depth 1
    git clone https://github.com/aura-systems/IL2CPU.git c:\IL2CPU --depth 1
    
build_script:
- cmd: |
    rem %APPVEYOR_BUILD_FOLDER%
    msbuild "c:\Cosmos\Builder.sln" /t:Restore;Build /p:Platform="Any CPU" /p:Configuration=Debug /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    msbuild "c:\Cosmos\Build.sln" /t:Restore;Build /p:Platform="Any CPU" /p:Configuration=Debug /p:OutputPath="%APPVEYOR_BUILD_FOLDER%\Build\VSIP" /p:DeployExtension=false /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    msbuild "c:\Cosmos\Test.sln" /t:Restore;Build /p:Platform="Any CPU" /p:Configuration=Debug /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
    msbuild "Aura Operating System\Aura OS.sln" /t:Restore;Build /p:Platform="Any CPU" /p:Configuration=Debug /maxcpucount /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

#test: off
#  assemblies:
#  - Cosmos.Core.Memory.Test.dll
#  - DebugCompiler.dll
#  - Cosmos.TestRunner.UnitTest.dll

on_finish:
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", "c:\Aura_OS\TestResult.xml")

matrix:
  fast_finish: true

artifacts:
  - path: '**\TestResult.xml'
